In [1]:
import numpy as np

In [2]:
v1 = np.array([3,12]) #Wektor v1
v1

array([ 3, 12])

In [3]:
np.linalg.norm(v1) #Norma Wektora, Dlugość wektora

12.36931687685298

In [4]:
v2 = np.array([-10,10,13]) # Wektor w przestrzeni R3

In [5]:
np.linalg.norm(v2) #Dlugość wektora


19.209372712298546

In [6]:
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(p - q)


5.0

In [7]:
p = np.array([3,0,1])
q = np.array([0,4, 2])
np.linalg.norm(p - q)
# Odległość dwóch punktów w przestrzeni R ^ 3 

5.0990195135927845

In [9]:
X = np.array([[2, 1, 1],
              [2, 3, 4]])
Y = np.array([[2, 2, 2],
              [4, 5, 6],
              [1, 2, 3]])
print(X, '\n')
print(Y)

[[2 1 1]
 [2 3 4]] 

[[2 2 2]
 [4 5 6]
 [1 2 3]]


In [10]:
Z = np.dot(X,Y) #Mnożenie macierzy 

In [12]:
Z

array([[ 9, 11, 13],
       [20, 27, 34]])

In [14]:
# Wyznacznik macierzy 
A = np.array([[2,3],[3,4]]) 
round(np.linalg.det(A))



-1

In [16]:
# Ślad Macierzy - Suma Elementów na przekątnej
A = np.array([[2,3],[5,6]])
np.trace(A)

8

In [18]:
np.eye(3, dtype = int) #Tworzenie macierzy jednostkowej

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [21]:
B = np.linalg.inv(A)
B



array([[-2.        ,  1.        ],
       [ 1.66666667, -0.66666667]])

In [23]:
np.set_printoptions(precision=4, suppress=True)
np.dot(B,A)

array([[ 1.,  0.],
       [-0.,  1.]])

In [27]:
np.transpose(A) #Transpozycja Macierzy

A.T

array([[2, 5],
       [3, 6]])

In [28]:
A = np.array([[2,4],[1,-1]])

In [29]:
B = np.array([[10], [-1]])

In [30]:
A_inv = np.linalg.inv(A)

In [31]:
X = np.dot(A_inv, B)

(2, 1)