In [1]:
import numpy as np

In [10]:
A = np.random.randn(20)
A = A.reshape(4,5)

In [11]:
np.set_printoptions(precision= 4)

In [13]:
A

array([[-1.2391,  1.6399, -0.7058, -0.5025,  0.9164],
       [ 0.1265,  0.8872,  2.5423,  0.2893,  0.9875],
       [ 1.2833,  1.0154, -0.2016,  0.2208, -0.3657],
       [ 0.0225, -0.417 ,  0.1571,  2.0379, -0.8514]])

In [15]:
A.sum() #Suma wszystkich elementów tablicy

7.84310431022147

In [18]:
A.sum(axis=0)

array([0.1933, 3.1256, 1.792 , 2.0455, 0.6868])

In [21]:
np.min(A, axis= 0)

array([-1.2391, -0.417 , -0.7058, -0.5025, -0.8514])

In [22]:
np.max(A, axis= 0 )

array([1.2833, 1.6399, 2.5423, 2.0379, 0.9875])

In [25]:
np.median(A, axis = 0)

array([ 0.0745,  0.9513, -0.0222,  0.255 ,  0.2753])

In [26]:
np.mean(A, axis = 0)

array([0.0483, 0.7814, 0.448 , 0.5114, 0.1717])

In [27]:
np.std(A, axis = 0)

array([0.8929, 0.7482, 1.2474, 0.9343, 0.7993])

In [28]:
np.var(A, axis= 0)

array([0.7974, 0.5598, 1.5559, 0.873 , 0.6389])

In [33]:
B = np.array([3.0, 123])

In [34]:
B

array([  3., 123.])

array([0.])