In [1]:
import numpy as np

In [4]:
np.random.seed(0)

In [5]:
np.random.randn()

1.764052345967664

Liczby Losowe z Rokładu Normalnego

In [6]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [7]:
np.random.randn(10,4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [10]:
np.random.rand(10, 4)

array([[0.36872517, 0.82099323, 0.09710128, 0.83794491],
       [0.09609841, 0.97645947, 0.4686512 , 0.97676109],
       [0.60484552, 0.73926358, 0.03918779, 0.28280696],
       [0.12019656, 0.2961402 , 0.11872772, 0.31798318],
       [0.41426299, 0.0641475 , 0.69247212, 0.56660145],
       [0.26538949, 0.52324805, 0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895, 0.66741038, 0.13179786],
       [0.7163272 , 0.28940609, 0.18319136, 0.58651293],
       [0.02010755, 0.82894003, 0.00469548, 0.67781654],
       [0.27000797, 0.73519402, 0.96218855, 0.24875314]])

Liczby z rokładu (0,1)

In [11]:
np.random.randint(10)

3

In [12]:
np.random.randint(low = 10, high=101)

82

In [13]:
np.random.randint(low = 10, high=101, size = 10)

array([36, 76, 62, 77, 71, 24, 14, 77, 21, 96])

Losowanie liczby całkowitych z zakresu 


In [14]:
np.random.choice([4,2,1,4])

2

Wybór losowego elementu z przesłanych danych

In [17]:
np.random.choice(['python','Java','SQL'])

'python'

In [18]:
data = np.arange(10)

In [19]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.random.shuffle(data) #Shuffle zmienia przesłane dane
#Działa na przesłany adresie obiektu 

In [21]:
data

array([2, 3, 6, 4, 9, 1, 7, 5, 8, 0])