In [1]:
import numpy as np

In [3]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [5]:
A[2]

2

In [6]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [7]:
A[:2]

array([0, 1])

In [9]:
A[[0,2]]

array([0, 2])

In [11]:
A = A.reshape(4,5)

In [12]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
A[1,1:4]

array([6, 7, 8])

In [30]:
A[1,1] =12

In [31]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5, 12,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])