In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,4,5,5])

In [3]:
arr

array([1, 2, 3, 4, 4, 5, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
diffarrray  = np.array((1,2,2,2,2))

In [7]:
type(diffarrray)

numpy.ndarray

In [8]:
arr = np.array(42)

In [9]:
arr

array(42)

In [11]:
arr = np.array([1,2,2,2])

In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [13]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [14]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [20]:
arr = np.array([1, 2, 3, 4], ndmin=5)

In [21]:
print(arr)

[[[[[1 2 3 4]]]]]


In [27]:
arr[0][0][0][0][0]

1

In [28]:
arr = np.array([1,2,2,4,5])

In [29]:
arr

array([1, 2, 2, 4, 5])

In [30]:
arr[2] + arr[3]

6

In [31]:
arr = np.array([[1,2,3,4], [2,3,4,5]])

In [32]:
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [33]:
arr[0][3]

4

In [35]:
bigarray = np.array([[[1,2],[1,2]],[[3,4],[5,6]]])

In [36]:
bigarray

array([[[1, 2],
        [1, 2]],

       [[3, 4],
        [5, 6]]])

In [38]:
bigarray[1]

array([[3, 4],
       [5, 6]])

In [41]:
bigarray[1][1][0]

5

In [45]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [49]:
arr[0:9]
arr[0:9:2]

array([1, 3, 5, 7, 9])

In [50]:
arr[4:]

array([ 5,  6,  7,  8,  9, 10])

In [60]:
arr[::3]

array([ 1,  4,  7, 10])

In [77]:
arr = np.array([[1, 2, 3, 3,2,6,7], [1, 4, 3, 4,2,7,9]])


In [78]:
arr

array([[1, 2, 3, 3, 2, 6, 7],
       [1, 4, 3, 4, 2, 7, 9]])

In [76]:
arr[1, 0:2]

array([1, 4])

In [83]:
a = arr[0:1, 1:4]

In [86]:
print(a)


[[2 3 3]]


In [97]:
arr = np.array((1,2,2,2), dtype='i4')
arr.dtype

dtype('int32')

In [100]:
new = arr.astype('i1')

In [101]:
print(arr.dtype, new.dtype)

int32 int8


In [102]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [103]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [172]:
def to_camel_case(text):
    text_c = text.split()
    for element in text:
        if element == '_':
            new_text = text.replace(element, '')
             
    for element in new_text:
        if element == '-':
            new_text = new_text.replace(element, '')
  
    return new_text
a = "_camel-case"


In [173]:
to_camel_case(a)

'camelcase'

In [191]:
def to_CC(text):
    fo

In [192]:
to_CC(a)

['_camel-case']