In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4])
B = np.array([2,1,2,1])

In [3]:
print(A)
print(B)

[1 2 3 4]
[2 1 2 1]


In [4]:
A+B

array([3, 3, 5, 5])

In [5]:
 A - B

array([-1,  1,  1,  3])

In [6]:
A * B

array([2, 2, 6, 4])

In [7]:
A / B

array([0.5, 2. , 1.5, 4. ])

In [8]:
A + 3 

array([4, 5, 6, 7])

In [9]:
A - 3

array([-2, -1,  0,  1])

In [10]:
np.add(A,B)

array([3, 3, 5, 5])

Dodawanie metoda Numpy

In [11]:
np.subtract(A,B)

array([-1,  1,  1,  3])

In [16]:
np.multiply(A, B)

array([2, 2, 6, 4])

In [12]:
2 * A

array([2, 4, 6, 8])

In [17]:
np.divide(A, B)

array([0.5, 2. , 1.5, 4. ])

In [13]:
A ** 2

array([ 1,  4,  9, 16])

In [14]:
A


array([1, 2, 3, 4])

In [21]:
X = np.array([[1,1], [1,1]])
Y = np.array([[1,2],[3,4]])
print(X)
print(Y)

[[1 1]
 [1 1]]
[[1 2]
 [3 4]]


In [20]:
np.dot(X,Y)

array([[4, 6],
       [4, 6]])

In [22]:
X.dot(Y)

array([[4, 6],
       [4, 6]])

In [23]:
Y.dot(X)

array([[3, 3],
       [7, 7]])

In [24]:
X@Y

array([[4, 6],
       [4, 6]])