In [2]:
import numpy as np

Importowanie bibliotek numpy


In [3]:
np.zeros(shape = (4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Generowanie macierzy zerowej o wymiarze 4 x 10

In [4]:
np.zeros(shape = (4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Generowanie macierzy zerowej o wymiarze 4 x 10 jednak z zachowaniem typu danych int

In [5]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Macierz jednostkowa 5 x 5 o całkowitym

In [6]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

Macierz tych samych wartości o wymiarze 3,3

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Generowanie tablicy 10cio elementowej

In [8]:
np.arange(start=0, stop=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Generowanie tablicy o danym starcie i stopie 

In [10]:
np.arange(start=0, stop=11, step=5)

array([ 0,  5, 10])

Dodano skok wartości w Tablicy

In [11]:
np.arange(start=10, stop=0, step=-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [14]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [23]:
np.linspace(start=1, stop=10, num=10, endpoint = True)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

linespace - dzieli dany zakres na ilosc elementów określoną parametrem 'num'

In [24]:
A = np.arange(15)

In [25]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
A[14]

14

In [35]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Reshape - pozwala zmienić wymiar tablicy, pod warunkiem, ze ilość elementnów się zgadza