In [ ]:
print('Hello, World')

Hello, World


In [1]:
import numpy as np 
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

### 1D Array

In [2]:
x = np.array([1,3])

Tworzenie Tablicy Numpy


In [3]:
x

array([1, 3])

Wyświetlanie tablicy

In [4]:
print(x)

[1 3]


Inny sposób wyświetlania


In [5]:
type(x)

numpy.ndarray

Typ Tablicy

In [6]:
x.ndim

1

Jej wymiar

In [7]:
x.shape

(2,)

Kształt tablicy

In [8]:
x.size

2

Liczba elementów tablcy

In [9]:
x.dtype

dtype('int32')

Typ danych w tablicy (tutaj liczba całkowita 64 bitowA)

In [10]:
x= np.array([1.3,1.5,7.5])

In [11]:
x

array([1.3, 1.5, 7.5])

In [12]:
x.dtype 

dtype('float64')

Typ danych (Liczba zmiennoprzecinkowa 64 bitowa)

## 2D Array

In [13]:
y = np.array([[1,2],[-3,1]])

Tablica 2wymiarowa


In [14]:
y.ndim

2

Wymiar macierzy

In [15]:
y.shape

(2, 2)

Kształt macierzy

In [16]:
z  = np.array([[1,2,4],[4,2,1]])

In [17]:
z

array([[1, 2, 4],
       [4, 2, 1]])

In [18]:
z.shape

(2, 3)

# 3D Array

In [19]:
x = np.array([[[4,1,3],
               [3,2,1]],
              [[3,1,1],
               [4,2,1]],
              [[2,3,1],
               [5,6,7]]
               ])

In [20]:
print(x)


[[[4 1 3]
  [3 2 1]]

 [[3 1 1]
  [4 2 1]]

 [[2 3 1]
  [5 6 7]]]


In [21]:
x.ndim

3

# Typy danych

In [22]:
A = np.array([1,2,3])
A.dtype

dtype('int32')

In [23]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [24]:
 A = np.array([1,2,3], dtype='complex')
A.dtype

dtype('complex128')

In [25]:
A = np.array([1.0, 2.7, 3.3], dtype = 'int')

In [26]:
A

array([1, 2, 3])

In [27]:
A.dtype

dtype('int32')

In [28]:
A = np.array([24,12,230], dtype = np.int8)


In [29]:
A = np.array([24,12,230], dtype = np.uint8)


In [30]:
A


array([ 24,  12, 230], dtype=uint8)

## Tworzenie Tablic



In [ ]:
np.zeros(shape =(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])